_target_: cdvae.pl_modules.gnn.DimeNetPlusPlusWrap
num_targets: ${data.num_targets}
hidden_channels: 128
num_blocks: 4
int_emb_size: 64
basis_emb_size: 8
out_emb_channels: 256
num_spherical: 7
num_radial: 6
otf_graph: ${data.otf_graph}
cutoff: 7.0
max_num_neighbors: 20
envelope_exponent: 5
num_before_skip: 1
num_after_skip: 2
num_output_layers: 3
readout: ${data.readout}