expname: test
max_num_atoms: 20 

# metadata specialised for each experiment
core:
  version: 0.0.1
  tags:
    - ${now:%Y-%m-%d}

hydra:
  run:
    dir: ${oc.env:HYDRA_JOBS}/singlerun/${now:%Y-%m-%d}/${expname}/
    
  sweep:
    dir: /home/gridsan/tmackey/hydra/singlerun/2023-10-28/og_CDVAE_mp_20
    subdir: ${hydra.job.num}_${hydra.job.id}

  job:
    env_set:
      WANDB_START_METHOD: thread
      WANDB_DIR: ${oc.env:WABDB_DIR}

defaults:
  - data: default
  - logging: default
  - model: vae
  - optim: default
  - train: default
#    Decomment this parameter to get parallel job running
  # - override hydra/launcher: joblib
